server:
  port: ${port:8089}
  servletPath: /

spring:
  application:
    name: insurance-service
  profiles:
    active: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true