apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: insurance
  name: insurance
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      run: insurance
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: insurance
    spec:
      containers:
      - image: gcr.io/uengine-istio-test/insurance:v15
        imagePullPolicy: IfNotPresent
        name: insurance
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

