apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: credit
  name: credit
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/credit
spec:
  replicas: 1
  selector:
    matchLabels:
      run: credit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: credit
    spec:
      containers:
      - image: gcr.io/uengine-istio-test/credit:v1
        imagePullPolicy: IfNotPresent
        name: credit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
