apiVersion: v1
kind: Service
metadata:
  labels:
    run: credit-service
  name: credit-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: credit-service
  sessionAffinity: None
  type: LoadBalancer
