apiVersion: v1
kind: Service
metadata:
  labels:
    run: credit
  name: credit
  namespace: default
  selfLink: /api/v1/namespaces/default/services/credit
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: credit
  sessionAffinity: None
  type: LoadBalancer
