server:
  port: ${port:8087}
  servletPath: /

spring:
  application:
    name: credit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true